version: '3.4'

services:
  service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - TokenSecret=
      - TokenLifetime=00:01:00
      - SmtpHost=smtp.example.com
      - SmtpPort=587
      - SmtpUser=
      - SmtpPass=
      - SmtpSecureSocketOptions=StartTls
      - EncryptionSecret=
      - ManagementUIEndpoint=
    ports:
      - "6004:80"
      - "6005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Shares\users:/mnt/users