name: Gated .net Build

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 
        with:
          submodules: true
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Setup .NET Core 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies 🔧
        run: dotnet restore ./IdentityManagementService.sln
      - name: Build 🔨
        run: dotnet build ./IdentityManagementService.sln --configuration Release --no-restore
      - name: Test 🧪
        run: dotnet test ./IdentityManagementService.sln --no-restore --verbosity normal
